### ISSUE TITLE
Android crash: com.square.moshi NoSuchMethodException

### ISSUE THREAD

**Issue by pavelparradomarin** [dixahq/dixa-messenger-react-native-demo#10]
It's not a single crash, affects a good amount of people. Mostly with Huawei and Android 8/9 ONLY.  65% of cases crash in the background.

```
Caused by java.lang.NoSuchMethodException: values []
       at java.lang.Class.getMethod(Class.java:2114)
       at java.lang.Class.getDeclaredMethod(Class.java:2093)
       at java.lang.Enum$1.create(Enum.java:268)
       at java.lang.Enum$1.create(Enum.java:263)
       at libcore.util.BasicLruCache.get(BasicLruCache.java:58)
       at java.lang.Enum.getSharedConstants(Enum.java:289)
       at java.lang.Class.getEnumConstantsShared(Class.java:2462)
       at java.lang.Class.getEnumConstants(Class.java:2448)
       at com.squareup.moshi.StandardJsonAdapters$EnumJsonAdapter.<init>(StandardJsonAdapters.java:273)
       at com.squareup.moshi.StandardJsonAdapters$1.create(StandardJsonAdapters.java:68)
       at com.squareup.moshi.Moshi.adapter(Moshi.java:146)
       at com.dixa.messenger.ofs.a.a(a.java:2)
       at com.dixa.messenger.settings.data.entity.SettingsDto_ElevioJsonAdapter.<init>(SourceFile:3)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
       at com.squareup.moshi.internal.Util.generatedAdapter(Util.java:588)
       at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:200)
       at com.squareup.moshi.Moshi.adapter(Moshi.java:146)
       at com.dixa.messenger.ofs.a.a(a.java:2)
       at com.dixa.messenger.settings.data.entity.SettingsDto_IntegrationsJsonAdapter.<init>(SourceFile:1)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
       at com.squareup.moshi.internal.Util.generatedAdapter(Util.java:588)
       at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:200)
       at com.squareup.moshi.Moshi.adapter(Moshi.java:146)
       at com.dixa.messenger.ofs.a.a(a.java:2)
       at com.dixa.messenger.settings.data.entity.SettingsDto_GeneralJsonAdapter.<init>(SourceFile:11)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
       at com.squareup.moshi.internal.Util.generatedAdapter(Util.java:588)
       at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:200)
       at com.squareup.moshi.Moshi.adapter(Moshi.java:146)
       at com.dixa.messenger.ofs.a.a(a.java:2)
       at com.dixa.messenger.settings.data.entity.SettingsDtoJsonAdapter.<init>(SourceFile:5)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
       at com.squareup.moshi.internal.Util.generatedAdapter(Util.java:588)
       at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:200)
       at com.squareup.moshi.Moshi.adapter(Moshi.java:146)
       at com.squareup.moshi.Moshi.adapter(Moshi.java:106)
       at retrofit2.converter.moshi.MoshiConverterFactory.responseBodyConverter(MoshiConverterFactory.java:89)
       at retrofit2.Retrofit.nextResponseBodyConverter(Retrofit.java:362)
       at retrofit2.Retrofit.responseBodyConverter(Retrofit.java:345)
       at retrofit2.HttpServiceMethod.createResponseConverter(HttpServiceMethod.java:124)
       at retrofit2.HttpServiceMethod.parseAnnotations(HttpServiceMethod.java:85)
       at retrofit2.ServiceMethod.parseAnnotations(ServiceMethod.java:39)
       at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:202)
       at retrofit2.Retrofit$1.invoke(Retrofit.java:160)
       at java.lang.reflect.Proxy.invoke(Proxy.java:913)
       at $Proxy7.getMessengerSettings()
       at com.dixa.messenger.ofs.D8$c.invokeSuspend(SourceFile:33)
       at com.dixa.messenger.ofs.D8$c.invoke(SourceFile:1)
       at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
       at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(BuildersKt__Builders_common.kt:169)
       at kotlinx.coroutines.BuildersKt.withContext(Builders.kt:1)
       at com.dixa.messenger.ofs.D8.c(SourceFile:79)
       at com.dixa.messenger.ofs.x8.a(SourceFile:1)
       at com.dixa.messenger.DixaMessenger$b.invokeSuspend(SourceFile:33)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:570)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
       ```

**Comment by idortulov** [comment]
Can you share what is the output from the following endpoint?

`https://messenger-edge.dixa.io/v1/messenger/settings?messengerToken=<MESSENGER KEY>`

Please replace `<MESSENGER KEY>` with your messenger key.

**Comment by professorkolik** [comment]
We have same issue, and it's a blocker for us from going Live

@idortulov here is the output 

```json
{
  "avatars": [],
  "style": {
    "theme": {
      "background": "midnight"
    }
  },
  "version": 1,
  "general": {
    "minimumIdentification": "ANONYMOUS",
    "availableLocales": [
      "en"
    ],
    "bulletinBoardEnabled": false,
    "bulletinBoardId": null,
    "description": {
      "ar": "لا تتردد في الاتصال بنا. نحن مستعدون للمساعدة.",
      "fr": "N'hésitez pas à nous contacter. Nous sommes là pour vous aider.",
      "is": "Hafðu endilega samband. Við erum tilbúin til að aðstoða.",
      "lv": "Droši sazinieties ar mums. Mēs labprāt palīdzēsim.",
      "pt": "Não hesite em contactar-nos. Estamos prontos para ajudar.",
      "it": "Sentiti libero di contattarci. Siamo pronti ad aiutarti.",
      "nl": "Neem gerust contact op. We staan klaar om u te helpen.",
      "et": "Võid meiega alati ühendust võtta. Oleme valmis sind aitama.",
      "de": "Zögere nicht, uns zu kontaktieren. Wir helfen dir gern.",
      "ru": "Обращайтесь, если возникнут вопросы. Мы будем рады помочь.",
      "sv": "Tveka inte att kontakta oss. Vi hjälper gärna till.",
      "da": "Ræk endelig ud. Vi er klar til at hjælpe.",
      "en": "Feel free to reach out. We're ready to help.",
      "es": "No dudes en contactarnos. Estamos encantados de ayudarte.",
      "fi": "Ota meihin yhteyttä, olemme apunasi.",
      "lt": "Nedvejodami kreipkitės – mielai padėsime.",
      "no": "Ta gjerne kontakt. Vi er klare til å hjelpe.",
      "hu": "Nyugodtan forduljon hozzánk. Mi készen állunk segíteni.",
      "pl": "Zawsze chętnie Ci pomożemy. Skontaktuj się z nami."
    },
    "title": {
      "ar": "مرحبًا بك 👋",
      "fr": "Bonjour 👋",
      "is": "Hæ 👋",
      "lv": "Sveiki! 👋",
      "pt": "Olá 👋",
      "it": "Ciao 👋",
      "nl": "Hallo daar 👋",
      "et": "Hei! 👋",
      "de": "Hallo 👋",
      "ru": "Привет 👋",
      "sv": "Hej 👋",
      "da": "Hey 👋",
      "en": "Hi there 👋",
      "es": "Hola 👋",
      "fi": "Hei siellä 👋",
      "lt": "Labas! 👋",
      "no": "Heisann 👋",
      "hu": "Üdv 👋",
      "pl": "Cześć! 👋 "
    }
  }
}
```

**Comment by professorkolik** [comment]
Here is the LogCat

```
V  Dixa messenger SDK was successfully initialized
E   Throwable: java.lang.IllegalArgumentException: Unable to create converter for class com.dixa.messenger.settings.data.entity.SettingsDto
    for method SettingsService.getMessengerSettings
    at retrofit2.Utils.methodError(Utils.java:54)
    at retrofit2.HttpServiceMethod.createResponseConverter(HttpServiceMethod.java:126)
    at retrofit2.HttpServiceMethod.parseAnnotations(HttpServiceMethod.java:85)
    at retrofit2.ServiceMethod.parseAnnotations(ServiceMethod.java:39)
    at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:202)
    at retrofit2.Retrofit$1.invoke(Retrofit.java:160)
    at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
    at $Proxy4.getMessengerSettings(Unknown Source)
    at com.dixa.messenger.ofs.C8$c.invokeSuspend(Unknown Source:36)
    at com.dixa.messenger.ofs.C8$c.invoke(SourceFile:1)
    at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
    at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
    at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
    at com.dixa.messenger.ofs.C8.a(Unknown Source:81)
    at com.dixa.messenger.ofs.w8.a(Unknown Source:2)
    at com.dixa.messenger.DixaMessenger$b.invokeSuspend(Unknown Source:34)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
    at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: com.dixa.messenger.ofs.n4.values []
    at java.lang.Enum.enumValues(Enum.java:270)
    at java.lang.Enum.access$000(Enum.java:61)
    at java.lang.Enum$1.create(Enum.java:277)
    at java.lang.Enum$1.create(Enum.java:275)
    at libcore.util.BasicLruCache.get(BasicLruCache.java:63)
    at java.lang.Enum.getSharedConstants(Enum.java:289)
    at java.lang.Class.getEnumConstantsShared(Class.java:2428)
    at java.lang.Class.getEnumConstants(Class.java:2414)
    at com.squareup.moshi.StandardJsonAdapters$EnumJsonAdapter.<init>(StandardJsonAdapters.java:273)
    at com.squareup.moshi.StandardJsonAdapters$1.create(StandardJsonAdapters.java:68)
    at com.squareup.moshi.Moshi.adapter(Moshi.java:146)
    at com.dixa.messenger.ofs.a.a(SourceFile:2)
    at com.dixa.messenger.settings.data.entity.SettingsDto_ElevioJsonAdapter.<init>(SourceFile:3)
    at java.lang.reflect.Constructor.newInstance0(Native Method)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
    at com.squareup.moshi.internal.Util.generatedAdapter(Util.java:588)
    at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:200)
    at com.squareup.moshi.Moshi.adapter(Moshi.java:146)
    at com.dixa.messenger.ofs.a.a(SourceFile:2)
    at com.dixa.messenger.settings.data.entity.SettingsDto_IntegrationsJsonAdapter.<init>(SourceFile:1)
    at java.lang.reflect.Constructor.newInstance0(Native Method)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
    at com.squareup.moshi.internal.Util.generatedAdapter(Util.java:588)
    at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:200)
    at com.squareup.moshi.Moshi.adapter(Moshi.java:146)
    at com.dixa.messenger.ofs.a.a(SourceFile:2)
    at com.dixa.messenger.settings.data.entity.SettingsDto_GeneralJsonAdapter.<init>(SourceFile:11)
    at java.lang.reflect.Constructor.newInstance0(Native Method)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
    at com.squareup.moshi.internal.Util.generatedAdapter(Util.java:588)

E   at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:200)
    at com.squareup.moshi.Moshi.adapter(Moshi.java:146)
    at com.dixa.messenger.ofs.a.a(SourceFile:2)
    at com.dixa.messenger.settings.data.entity.SettingsDtoJsonAdapter.<init>(SourceFile:5)
    at java.lang.reflect.Constructor.newInstance0(Native Method)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
    at com.squareup.moshi.internal.Util.generatedAdapter(Util.java:588)
    at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:200)
    at com.squareup.moshi.Moshi.adapter(Moshi.java:146)
    at com.squareup.moshi.Moshi.adapter(Moshi.java:106)
    at retrofit2.converter.moshi.MoshiConverterFactory.responseBodyConverter(MoshiConverterFactory.java:89)
    at retrofit2.Retrofit.nextResponseBodyConverter(Retrofit.java:362)
    at retrofit2.Retrofit.responseBodyConverter(Retrofit.java:345)
    at retrofit2.HttpServiceMethod.createResponseConverter(HttpServiceMethod.java:124)
    ... 22 more
Caused by: java.lang.NoSuchMethodException: com.dixa.messenger.ofs.n4.values []
    at java.lang.Class.getMethod(Class.java:2072)
    at java.lang.Class.getDeclaredMethod(Class.java:2050)
    at java.lang.Enum.enumValues(Enum.java:267)
    ... 65 more
Unable to fetch settings
```

**Comment by idortulov** [comment]
This has been fixed in version 1.3.6.

**Comment by pavelparradomarin** [comment]
Thank you!

**Comment by idortulov** [comment]
@pavelparradomarin Are you still having issues? Do you have any additional questions? Can we close this ticket?

**Comment by pavelparradomarin** [comment]
Didn't spot any issue. The ticket can be closed.

**Comment by sizmin** [comment]
@idortulov it happens again in 1.4.0 for me.

**Comment by idortulov** [comment]
Try version 1.4.1. @sizmin
